<?php

use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;
use Fisharebest\Webtrees\Http\RequestHandlers\ModulesAllPage;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use Illuminate\Database\Capsule\Manager as DB;
use Illuminate\Database\Query\Expression;

/**
 * @var string		    $module
 * @var int		    $tree_id
 * @var string		    $tree_name
 * @Var <int,string>	    $tab_info
 * @var string		    $cancel
 * @var array		    $btype_arr
 */

?>
<h2><?= $tab_info[1] . ' - ' . I18N::translate('Preferences') ?></h2>

<form method="post">
    <input type="hidden" name="save" value="1">
    <?= csrf_field() ?>
    <input type="hidden" name="tree" value="<?= $tree_id ?>">
    <input type="hidden" name="tab" value="<?= $tab_info[0] ?>">
<?php
    $i = 0;
    foreach($btype_arr as $value) {
	$i++;
?>
    <input type="hidden" name="info[<?= $value['rin'] ?>]" value="<?= $value['info'] ?>">
<?php
    }
?>
    <table
	class="table table-bordered table-sm wt-table-booktype datatables d-none"
	<?= view('lists/datatables-attributes') ?>
	data-paging=false data-filter=false data-info=false>
	<thead>
	    <tr>
		<th><?= I18N::translate('Book type') ?></th>
		<th class="col-sm-2"><?= I18N::translate('bookDB RIN') ?></th>
		<th class="col-sm-2"><?= I18N::translate('Show') ?></th>
		<th class="col-sm-2"><?= I18N::translate('Id (in %s)', $tree_name) ?></th>
	    </tr>
	</thead>
	<tbody>
<?php
    $i = 0;
    foreach($btype_arr as $value) {
	$i++;
	$field1 = "btype[" . $value['rin'] . "]";
	$field2 = "show[" . $value['rin'] . "]";
	$label1 = I18N::translate('Add book type');
	$label2 = I18N::translate('Change');
	$info = I18N::translate($value['info']);
?>
	    <tr>
		<td data-sort="<?= $info ?>"><?= $info ?></td>
		<td data-sort="<?= $value['rin'] ?>"><?= $value['rin'] ?></td>
<?php
	if ($value['id'] == '')	{
?>
	    <td>&nbsp;</td>
	    <td><?= view('components/checkbox', ['label' => $label1, 'name' => $field1, 'checked' => (bool) 0, 'value' => $value['info']]) ?></td>
<?php
	} else {
	    $status = ($value['nothidden']) ? view('icons/save') : view('icons/cancel');
?>
	    <td><div class="form-inline"><?= $status ?>&nbsp;<?= view('components/checkbox', ['label' => $label2, 'name' => $field2, 'checked' => (bool) 0, 'value' => $value['id']]) ?></div></td>
	    <td><?= e($value['rin']) ?></td>
<?php
	}
?>
	    </tr>
<?php
    }
?>
	</tbody>
    </table>
    <div class="row form-group">
	<div class="offset-sm-3 col-sm-9">
	    <button type="submit" class="btn btn-primary">
		<?= view('icons/save') ?>
		<?= I18N::translate('save') ?>
	    </button>
	    <a class="btn btn-secondary" href="<?= e($cancel) ?>">
		<?= view('icons/cancel') ?>
		<?= I18N::translate('cancel') ?>
	    </a>
	</div>
    </div>
</form>